name: Build and publish

on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker compose up
    - name: Upload Artifact
      uses: actions/upload-artifact@v4 
      with:
        name: executables
        path: |
          *.AppImage
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build (Windows)
      run: docker compose -f docker-compose.windows.yml up
    - name: Make Windows Installer
      run: ./create_windows_installer.sh
    - name: Zip Portable Windows Artifact
      run: zip -r windows-portable.zip package
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: |
          *.zip
          *.exe
          
  publish:
    needs: [build, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v4
    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/*.AppImage
          **/*.zip
          **/*.exe
