name: Rust

on:
  push:
  pull_request:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose up
    - name: Build (Windows)
      run: docker-compose -f docker-compose.windows.yml up
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: executables
        path: |
          '**.AppImage'
          '**.zip'
    - name: ls
      run: ls

    - name: pwd
      run: pwd
      
